# Generated by Django 5.2.5 on 2025-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pipeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
